### PR TITLE
added details and example on usage of teamcity.default.properties file

### PR DESCRIPTION
**Pull request by wachtel1**

### CODE REVIEW

**Comment by wachtel1** [comment]
Additional testing showed that there is something wrong here. Let me double-check and get back to it.

**Comment by wachtel1** [comment]
Additional testing showed that this parameter isn't working correctly: https://youtrack.jetbrains.com/issue/TW-90130

**Comment by Valrravn** [comment]
> Additional testing showed that this parameter isn't working correctly: https://youtrack.jetbrains.com/issue/TW-90130

so... Do I merge this or not? :)

**Comment by wachtel1** [comment]
I will close it, as it's currently unclear. Let's wait for the fix/explanation. I will then recreate.

**Pull request closed without merging**
